apiVersion: apps/v1
kind: Deployment
metadata:
  name: labdeployment
spec:
  replicas: 3
  selector:
  -  matchLabels:
      app: web  
  template:    
    metadata:
      labels:
       app: web
    spec:   
      image: fabricioveronez/web-page:blue 
      ports: 
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web  
  ports: 
     - port: 80
       protocol: tcp
  type: NodePort     

